services:
  plaza-order-no-provider-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 'plaza-order-no-provider:latest'
    environment:
      - spring.cloud.nacos.discovery.ip=${DEV_HOST} # 不同物理机必须明确指定IP
      - DUBBO_IP_TO_REGISTRY=${DEV_HOST}
      - DUBBO_PORT_TO_BIND=29205            # 容器内 Dubbo 服务绑定的端口（会覆盖 dubbo.protocol.port）
      - NACOS_HOST=${DEV_HOST}
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
    ports:
      - '29205:29205'
    volumes:
      - D:\tmp\logs\plaza-order-no-provider-1:/tmp/logs/plaza-order-no-provider

#  plaza-order-no-provider-2:
#    image: 'plaza-order-no-provider:latest'
#    environment:
#      - spring.cloud.nacos.discovery.ip=${DEV_HOST} # 不同物理机必须明确指定IP
#      - DUBBO_IP_TO_REGISTRY=${DEV_HOST}
#      - DUBBO_PORT_TO_BIND=29215            # 容器内 Dubbo 服务绑定的端口（会覆盖 dubbo.protocol.port）
#      - NACOS_HOST=${DEV_HOST}
#      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
#    ports:
#      - '29215:29215'
#    volumes:
#      - D:\tmp\logs\plaza-order-no-provider-2:/tmp/logs/plaza-order-no-provider