spring:
  cloud:
    stream:
      function:
        definition: orderTimeout;stockDeduct;cartChange;orderPaid;seckillStockDeduct
      default:
        content-type: application/json
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-multiplier: 2.0
          back-off-max-interval: 10000
      bindings:
        orderPaid-out-0:
          destination: order-paid-topic
        orderPaid-in-0:
          destination: order-paid-topic
          group: order-paid-group
        orderTimeout-out-0:
          destination: order-timeout-topic
        orderTimeout-in-0:
          destination: order-timeout-topic
          group: order-timeout-group
        stockDeduct-out-0:
          destination: stock-deduct-topic
        stockDeduct-in-0:
          destination: stock-deduct-topic
          group: stock-deduct-group
        seckillStockDeduct-in-0:
          destination: seckill-stock-deduct-topic
          group: seckill-stock-deduct-group
          consumer:
            max-attempts: 1 # 不做额外重试
        cartChange-out-0:
          destination: cart-change-topic
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_HOST:127.0.0.1}:9876
        bindings:
          seckillStockDeduct-in-0:
            consumer:
              max-reconsume-times: 5  # 最多重投5次后进入死信队列

rocketmq:
  name-server: ${ROCKETMQ_HOST:127.0.0.1}:9876
  producer:
    group: seckill-order-tx-producer-group
