spring:
  cloud:
    stream:
      function:
        definition: orderTimeout;stockDeduct;cartChange;orderPaid;orderReserve;orderRefund
      default:
        content-type: application/json
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
          back-off-multiplier: 2.0
          back-off-max-interval: 10000
      bindings:
        orderPaid-out-0:
          destination: order-paid-topic
        orderPaid-in-0:
          destination: order-paid-topic
          group: order-paid-group
        orderTimeout-out-0:
          destination: order-timeout-topic
        orderTimeout-in-0:
          destination: order-timeout-topic
          group: order-timeout-group
        stockDeduct-out-0:
          destination: stock-deduct-topic
        stockDeduct-in-0:
          destination: stock-deduct-topic
          group: stock-deduct-group
        cartChange-out-0:
          destination: cart-change-topic
        orderReserve-out-0:
          destination: order-reserve-topic
        orderReserve-in-0:
          destination: order-reserve-topic
          group: order-reserve-group
        orderRefund-out-0:
          destination: order-refund-topic
        orderRefund-in-0:
          destination: order-refund-topic
          group: order-refund-group
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_HOST:127.0.0.1}:9876

rocketmq:
  name-server: ${ROCKETMQ_HOST:127.0.0.1}:9876
  producer:
    group: seckill-order-tx-producer-group
