config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
    username: nacos
    password: nacos

spring:
  cloud:
    nacos:
      username: ${config.nacos.username}
      password: ${config.nacos.password}
      discovery:
        server-addr: ${config.nacos.host}
        namespace: dev
    stream:
      function:
        definition: cartChange
      bindings:
        cartChange-out-0:
          destination: cart-change-topic
          content-type: application/json
        cartChange-in-0:
          destination: cart-change-topic
          group: cart-change-group
          content-type: application/json
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/plaza?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:127.0.0.1}
      database: 3
      lettuce:
        pool:
          min-idle: 1
          max-idle: 5
          max-active: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl